# Generated by Django 4.1.3 on 2022-11-05 17:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lodging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Hotel", "Hotel"),
                            ("Resort", "Resort"),
                            ("Pousada", "Pousada"),
                        ],
                        default="Hotel",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("name", models.CharField(max_length=127)),
                ("state", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=127)),
                ("district", models.CharField(max_length=127)),
                ("street", models.CharField(max_length=127)),
                (
                    "number",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("complement", models.CharField(blank=True, max_length=30)),
                ("cep", models.CharField(max_length=8)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lodging",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
