# Generated by Django 4.1.3 on 2022-11-01 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Hotel', 'Hotel'), ('Resort', 'Resort'), ('Pousada', 'Pousada')], default='Hotel', max_length=20)),
                ('name', models.CharField(max_length=127)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=127)),
                ('district', models.CharField(max_length=127)),
                ('street', models.CharField(max_length=127)),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('complement', models.CharField(blank=True, max_length=30)),
                ('cep', models.CharField(max_length=8)),
            ],
        ),
    ]
