# Generated by Django 4.1.3 on 2022-11-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lodgings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lodging",
            name="email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lodging",
            name="phone",
            field=models.CharField(default="", max_length=12),
            preserve_default=False,
        ),
    ]
