# Generated by Django 4.1.3 on 2022-11-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lodgings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lodging",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="lodging",
            name="phone",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name="lodging",
            name="category",
            field=models.CharField(
                choices=[
                    ("hotel", "Hotel"),
                    ("resort", "Resort"),
                    ("pousada", "Pousada"),
                ],
                default="hotel",
                max_length=20,
            ),
        ),
    ]
