# Generated by Django 4.1.3 on 2022-11-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lodgings", "0002_lodging_email_lodging_phone_alter_lodging_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lodging",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="lodging",
            name="phone",
            field=models.CharField(max_length=12),
        ),
    ]
