# Generated by Django 4.1.3 on 2022-11-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodgings', '0003_alter_lodging_email_alter_lodging_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodging',
            name='category',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Resort', 'Resort'), ('Pousada', 'Pousada')], default='Hotel', max_length=20),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
