# Generated by Django 4.1.3 on 2022-11-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lodgings", "0003_alter_lodging_email_alter_lodging_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lodging",
            name="category",
            field=models.CharField(
                choices=[
                    ("hotel", "Hotel"),
                    ("resort", "Resort"),
                    ("pousada", "Pousada"),
                ],
                default="hotel",
                max_length=20,
            ),
        ),
    ]
